INSERT INTO questions (category, difficulty, question, answer, wrongOne, wrongTwo, wrongThree) 
 VALUES
 ("Movies", 1 ,'How many movies are there in the Harry Potter Series?', '7', '5', '9', '4'),
 ("Movies", 3 ,'Name this movie: You take the blue pill - the story ends, you wake up in your bed and believe whatever you want to believe. You take the red pill - you stay in Wonderland and I show you how deep the rabbit-hole goes.', 'The Matrix', 'The Lion King', 'Dumb & Dumber', 'Twilight'),
 ("Movies", 5 ,'What movie is the character Norman Bates from?', 'Psycho', 'Pet Cemetary', 'Nightmare on Elme Street', 'Cinderella'),
 ("Movies", 4 ,'What secret agent is code named 007?', 'James Bond', 'Tony Stark', 'Jason Bourne', 'James Carter'),
 ("Movies", 2 ,'What giant shark made a huge debut on the big screen?', 'Jaws', 'Bruce', 'Lenny', 'Mega Shark'),
 ("Movies", 7 ,'What is the name of the hobbit played by Elijah Wood in the Lord of the Rings movies?', 'Frodo', 'Gimli', 'Arwen', 'Eragon'),
 ("Movies", 7 ,'What movie has won the most oscars?', 'Titanic', 'Lord of the Rings', 'Shark Tale', 'The Notebook'),
 ("Movies", 9 ,'What actor died during the filming of Gladiator?', 'Oliver Reed', 'Christian Bale', 'Leonardo Dicapio', 'Russel Crowe'),
 ("Movies", 8 ,'In the Wizard of Oz, name the Good Witch of the North?', 'Glinda', 'MaryAnn', 'Elsa', 'Queen Willow'),
 ("Movies", 10 ,'Between 1937 and 2018, how many Disney Movies have been produced?', '738', '565', '989', '354'),

 ("Geography", 3 ,"What is the world's biggest island?", "Greenland", "The Philipines", "Australia", "New Zealnd"),
 ("Geography", 1 ,"What is the world's longest river?", "Nile", "Amazon", "Colorado", "Rhine"),
 ("Geography", 2 ,"What is the world's biggest ocean?", "Pacific", "Atlantic", "Indian", "Arctic"),
 ("Geography", 8 ,"What is the diameter of Earth?", "8,000 miles", "9,000 miles", "12,000 miles", "15,000 miles"),
 ("Geography", 10 ,"What country would you find the Cresta Run?", "Switzerland", "Germany", "Sweden", "United States"),
 ("Geography", 10 ,"Which African country used to be called Abyssinia?", "Ethipia", "Egypt", "Uganda", "Ivory Coast"),
 ("Geography", 5 ," In which U.S. state is Death Valley?", "California", "Nevada", "Arizona", "New Mexico"),
 ("Geography", 4 ," What is the national emblem of Canada?", "The Mape leaf", "Bear", "Snowflake", "Beaver"),
 ("Geography", 6 ,"Which is the least populated U.S. state?", "Wyoming", "Rhode Island", "North Dakota", "Montana"),
 ("Geography", 9 ," The Taj Mahal is located in which Indian city?", "Agra", "New Dehli", "Taj", "Mumbai"),

 ("History", 6 ," When did Margaret Thatcher become Prime Minister?", "1979", "1982", "1965", "1985"),
 ("History", 5 ," When was William Shakespeare born?", "1564", "1588", "1560", "1499"),
 ("History", 3 ," When did the Cold War end?", "1989", "1991", "1980", "1985"),
 ("History", 1 ," When was the euro introduced as legal currency on the world market?", "1999", "2001", "1990", "1989"),
 ("History", 10 ," In 1927, who became the first man to fly solo and non-stop across the Atlantic?", "Charles Lindberg", "Amelia Earhart", "Jimmy Doolittle", "Glenn Curtiss"),
 ("History", 4 ," What was the family name of the Russian rulers from the 17th century until the 1917 revolution?", "Romanov", "Putinov", "Ramisov", "Stolslov"),
 ("History", 7 ," In which country did the Easter Rising take place in 1916?", "Ireland", "England", "France", "United States"),
 ("History", 1 ," Who was president during the U.S. Civil War?", "Abraham Lincoln", "George Washington", "John Adams", "John Hamilton"),
 ("History", 10 ," Which Greek historian is known as the Father of History?", "Herodotus", "Cassius Dio", "Thucydides", "Xenophon"),
 ("History", 10 ," An expedition led by Roald Amundsen became the first to reach what on December 14, 1911?", "South Pole", "North Pole", "Arctic Circle", "Grand Canyon"),

 ("Random Trivia", 4 ," Which singer’s real name is Stefani Joanne Angelina Germanotta?", "Lady Gaga", "Cher", "Toni Braxton", "Britney Spears"),
 ("Random Trivia", 1 ," How many players are there in a baseball team?", "9", "10", "12", "15"),
 ("Random Trivia", 5 ," The average human body contains how many pints of blood?", "9", "16", "20", "50"),
 ("Random Trivia", 6 ," In which city is Jim Morrison buried?", "Paris", "New Dehli", "London", "Los Angeles"),
 ("Random Trivia", 3 ," Hg is the chemical symbol of which element?", "Mercury", "Iron", "Sodium", "Gold"),
 ("Random Trivia", 1 ," In Fahrenheit, at what temperature does water freeze?", "32", "34", "35", "29"),
 ("Random Trivia", 2 ," What is Chandler’s last name in the sitcom Friends?", "Bing", "Jones", "Kramer", "Smith"),
 ("Random Trivia", 1 ," The Statue of Liberty was given to the US by which country?", "France", "England", "Spain", "Italy"),
 ("Random Trivia", 10 ," According to Greek mythology who was the first woman on earth?", "Pandora", "Eve", "Saraclys", "Athena"),
 ("Random Trivia", 9 ," How many letters are there in the German alphabet?", "30", "32", "20", "85"),

('Sports', 4 ,'Which is the only American Football team to go a whole season undefeated, including the Super Bowl?', 'Dolphins', 'Packers', 'Cowboys', 'Patriots'),
('Sports', 5 ,' Which is the only team to play in every soccer World Cup tournament?', 'Brazil', 'Italy', 'Germany', 'England'),
('Sports', 10 ,' How is soccer player Edson Arantes do Nascimento better known?', 'Pele', 'Ronaldo', 'Ronaldinho', 'Maradona'),
('Sports', 8 ,'Which NFL team appeared in four consecutive Super Bowls from 1991 - 1994 and lost them all?', 'Bills', 'Packers', 'Dolphins', 'Cowboys'),
('Sports', 6 ,' Which country won the first ever soccer World Cup in 1930?', 'Uruguay', 'Brazil', 'Argentina', 'Germany'), 
('Sports', 9 ,'In which year was the first Wimbledon tournament held?', '1877', '1956', '1923', '1965'),
('Sports', 6 ,'In the NFL, what team was originally named the New York Titans?', 'The New York Jets', 'San Diego Chargers', 'New York Giants', 'New England Patriots'),
('Sports', 8 ,'What team won 3 Super Bowls in the 1990s?', 'Cowboys', 'Titans', 'Cardinals', 'Steelers'),
('Sports', 9 ,'In the NBA, the Celtics won the NBA Championship for the 2007-08 season. Who did they defeat?', 'LA Lakers', 'Dallas Mavericks', 'Golden State Warriors', 'Houston Rockets'),
('Sports', 7 ,'Who was the youngest player in the NBA to reach 10,000 regular season points in the 20th century?', 'Kobe Bryant', 'Stephen Curry', 'Lebron James', 'James Harden')
